name: Trigger Cypress Tests

on:
  push:
    branches:
      - master
jobs:
  trigger-cypress-tests:
    runs-on: ubuntu-22.04
    steps:
     - name: Delay for 4 minutes
        run: sleep 240s
      - name: Trigger Cypress Pipeline
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await octokit.actions.createWorkflowDispatch({
              owner: 'Ygor Mendes',
              repo: 'cypress',
              workflow_id: 'https://github.com/YgorMendes/cypress/actions/workflows/ci.yaml' 
            });
            console.log(data);
