name: Trigger Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 1 minute
        run: sleep 60s  # Espera por 1 minuto
        
      - name: Trigger Cypress Pipeline
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.repos.createDispatchEvent({
              owner: 'YgorMendes',
              repo: 'cypress',
              event_type: 'https://github.com/YgorMendes/cypress/actions/workflows/ci.yaml'
            });
            console.log(response);
