name: Trigger Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-cypress-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Delay for 1 minute
        run: sleep 60s  # 60 segundos = 1 minuto

      - name: Trigger Cypress Pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const { Octokit } = require('@octokit/core');
          const { createTokenAuth } = require('@octokit/auth-token');

          const auth = createTokenAuth(process.env.GITHUB_TOKEN);
          await auth();

          const octokit = new Octokit({
            auth: auth.token,
          });

          // Use a URL completa da ação do GitHub Actions
          await octokit.request('POST /repos/YgorMendes/cypress/actions/workflows/ci.yaml/dispatches', {
            ref: 'master',  // Branch alvo da execução
          });

          console.log('Pipeline Cypress disparada com sucesso.');
