name: Trigger Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 1 minute
        run: sleep 60s

      - name: Trigger Cypress Pipeline
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require('@octokit/core');
            const { createTokenAuth } = require('@octokit/auth-token');

            const auth = createTokenAuth(process.env.GITHUB_TOKEN);
            await auth();

            const octokit = new Octokit({
              auth: auth.token,
            });

            // Use a URL completa da ação do GitHub Actions no repositório do Cypress
            await octokit.request('POST /repos/YgorMendes/cypress/actions/workflows/ci.yaml/dispatches', {
              ref: 'master',
            });

            console.log('Pipeline Cypress disparada com sucesso.');
