name: Trigger Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 1 minute
        run: sleep 60s

      - name: Trigger Cypress Pipeline
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/YgorMendes/cypress/actions/workflows/ci.yaml/dispatches \
            -d '{"ref": "master"}'
