name: Trigger Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 1 minute
        run: sleep 60s  # 60 segundos = 1 minuto

      - name: Trigger Cypress Pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node trigger-cypress.js
